name: 'Harry262000'
description: 'Generate a 3D contribution graph for your GitHub profile'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  USERNAME:
    description: 'GitHub username'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
